### ISSUE TITLE
train.py failing in sugartensor

### ISSUE THREAD

**Issue by LukasMosser** [buriburisuri/SRGAN#1]
When running train.py using newest tensorflow release on windows
and python 3.5 I get following trace:

`Traceback (most recent call last):
  File "train.py", line 51, in <module>
    .sg_periodic_shuffle(factor=2)
  File "E:\Anaconda3\lib\site-packages\sugartensor\sg_main.py", line 151, in wrapper
    out = func(tensor, tf.sg_opt(kwargs))
  File "E:\Anaconda3\lib\site-packages\sugartensor\sg_transform.py", line 543, in sg_periodic_shuffle
    for i in range(channel_target):
TypeError: 'float' object cannot be interpreted as an integer`

Any idea on what might be going wrong?

**Comment by buriburisuri** [comment]
@LukasMosser  Thank you for you information.  That's because division difference between python 2.7 and 3.4.  I'll patch this issue at next sugartensor soon.  Please, use python 2.7 instead of 3.4 until next patch.

**Comment by LukasMosser** [comment]
@buriburisuri many thanks! I should've spotted that too :)

**Comment by buriburisuri** [comment]
@LukasMosser I've patched this at ver 0.0.2.4.  Thank you.
